name: Programowanie full-stack w chmurze obliczeniowej
on:
#  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-push-images:
    # Definicja systemu do instalacji
    name: Sprawozdanie 2
    runs-on: ubuntu-latest

    steps:

      # Sprawdzenie czy workflow ma poprawny dostęp do repo
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Instalacja QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      # Instalacja środowiska Docker + Buildx
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2
        
      # Logowanie do Dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Budowa obrazu dla dwóch architektur sprzętowych oraz przesłanie do repo na Dockerhub
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64/v8,linux/amd64 
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            matiz2115/chmura:tagname
